In [ ]:
import pandas as pd


In [ ]:
pd.__version__

'2.2.2'

In [ ]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [ ]:
series=pd.Series(lst)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
empty = pd.Series([])
print(empty)

Series([], dtype: object)


In [ ]:
a = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
a = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'],name="alphabets")
print(a)

a    1
b    2
c    3
d    4
e    5
Name: alphabets, dtype: int64


In [ ]:
scalar_series = pd.Series(5)
print(scalar_series)

0    5
dtype: int64


In [ ]:
scalar_series = pd.Series(5, index=[0,1,2,3,4])
print(scalar_series)

0    5
1    5
2    5
3    5
4    5
dtype: int64


In [ ]:
dict= pd.Series({"a":1,"b":2,"c":3,"d":4,"e":5})
print(dict)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
dict[0:2]

a    1
b    2
dtype: int64

In [ ]:
dict.max()

5

In [ ]:
new_dict=pd.Series({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9]})
print(new_dict)

a    [1, 2, 3]
b    [4, 5, 6]
c    [7, 8, 9]
dtype: object


In [ ]:
lst = [1,2,3,4,5]
df= pd.DataFrame(lst)
df

,0
0,1
1,2
2,3
3,4
4,5


In [ ]:
lst = [[1,2,3,4,5],[4,5,6,7,8]]
df =pd.DataFrame(lst)
df

,0,1,2,3,4
0,1,2,3,4,5
1,4,5,6,7,8


In [ ]:
a= pd.DataFrame([{"a":1,"b":2,"c":3,"d":4,"e":5},
                {"a":6,"b":7,"c":8,"d":9,"e":10}],index=["row1","row2"])
print(a)

      a  b  c  d   e
row1  1  2  3  4   5
row2  6  7  8  9  10


In [ ]:
import numpy as np
import pandas as pd
b={"Name":["Tejas","Rohit","Suresh"],
   "Age":pd.Series([25,30,35]),
   "City":["Pune","Mumbai","Delhi"]}
df = pd.DataFrame(b)
print(df)

     Name  Age    City
0   Tejas   25    Pune
1   Rohit   30  Mumbai
2  Suresh   35   Delhi


In [ ]:
df = pd.read_csv(r"C:\Users\Tejas\Desktop\datasets\ecommerce_customer_behavior_dataset.csv")
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_001337,CUST_01337,2023-01-01,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5
1,ORD_004885,CUST_04885,2023-01-01,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3
2,ORD_004507,CUST_04507,2023-01-01,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2
3,ORD_000645,CUST_00645,2023-01-01,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4
4,ORD_000690,CUST_00690,2023-01-01,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4


In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_001337,CUST_01337,2023-01-01,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5
1,ORD_004885,CUST_04885,2023-01-01,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3
2,ORD_004507,CUST_04507,2023-01-01,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2
3,ORD_000645,CUST_00645,2023-01-01,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4
4,ORD_000690,CUST_00690,2023-01-01,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4


In [ ]:
df.tail(
)

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
4995,ORD_001048,CUST_01048,2024-03-26,18,Female,Izmir,Beauty,130.35,1,27.30,103.05,Bank Transfer,Mobile,17,10,False,9,1
4996,ORD_001051,CUST_01051,2024-03-26,27,Male,Adana,Beauty,71.55,1,0.00,71.55,Debit Card,Mobile,13,9,True,6,4
4997,ORD_003543,CUST_03543,2024-03-26,45,Female,Antalya,Food,39.38,1,5.27,34.11,Digital Wallet,Mobile,38,10,True,5,4
4998,ORD_004443,CUST_04443,2024-03-26,41,Female,Istanbul,Fashion,171.19,1,0.00,171.19,Credit Card,Mobile,20,12,True,5,4
4999,ORD_000902,CUST_00902,2024-03-26,30,Female,Konya,Books,84.30,4,21.72,315.48,Debit Card,Desktop,8,9,True,5,5


In [ ]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Date', 'Age', 'Gender', 'City',
       'Product_Category', 'Unit_Price', 'Quantity', 'Discount_Amount',
       'Total_Amount', 'Payment_Method', 'Device_Type',
       'Session_Duration_Minutes', 'Pages_Viewed', 'Is_Returning_Customer',
       'Delivery_Time_Days', 'Customer_Rating'],
      dtype='object')

In [ ]:
df.size

90000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Order_ID                  5000 non-null   object 
 1   Customer_ID               5000 non-null   object 
 2   Date                      5000 non-null   object 
 3   Age                       5000 non-null   int64  
 4   Gender                    5000 non-null   object 
 5   City                      5000 non-null   object 
 6   Product_Category          5000 non-null   object 
 7   Unit_Price                5000 non-null   float64
 8   Quantity                  5000 non-null   int64  
 9   Discount_Amount           5000 non-null   float64
 10  Total_Amount              5000 non-null   float64
 11  Payment_Method            5000 non-null   object 
 12  Device_Type               5000 non-null   object 
 13  Session_Duration_Minutes  5000 non-null   int64  
 14  Pages_Vi

In [ ]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.00000,5000.000000,5000.000000
mean,35.032600,455.834120,2.220000,24.852804,983.108914,14.57340,8.98420,6.497000,3.902800
std,11.080546,712.477209,1.398711,88.385124,1898.978528,8.66575,2.80434,3.464966,1.128542
min,18.000000,5.180000,1.000000,0.000000,7.870000,1.00000,1.00000,1.000000,1.000000
25%,27.000000,76.587500,1.000000,0.000000,122.517500,8.00000,7.00000,4.000000,3.000000
50%,35.000000,182.950000,2.000000,0.000000,337.910000,13.00000,9.00000,6.000000,4.000000
75%,42.000000,513.930000,3.000000,8.760000,979.695000,19.00000,11.00000,8.000000,5.000000
max,75.000000,7159.450000,5.000000,1525.550000,22023.900000,73.00000,24.00000,25.000000,5.000000


In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df=pd.DataFrame({"a":[1,2,3,4,5]},index=[0,1,2,3,4])
print(df)

   a
0  1
1  2
2  3
3  4
4  5


In [ ]:
df = pd.read_csv(r"C:\Users\Tejas\Desktop\datasets\sales_data.csv")
df.head()
df.tail()
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Product_ID            1000 non-null   int64  
 1   Sale_Date             1000 non-null   object 
 2   Sales_Rep             1000 non-null   object 
 3   Region                1000 non-null   object 
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64  
 6   Product_Category      1000 non-null   object 
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object 
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object 
 12  Sales_Channel         1000 non-null   object 
 13  Region_and_Sales_Rep  1000 non-null   object 
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB


In [4]:
df=pd.read_csv(r"C:\Users\Tejas\Desktop\datasets\data.csv")
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  32 non-null     int64  
 1   Date      31 non-null     object 
 2   Pulse     32 non-null     int64  
 3   Maxpulse  32 non-null     int64  
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB


In [5]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [6]:
df.isnull()

,Duration,Date,Pulse,Maxpulse,Calories
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False


In [7]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [8]:
df.shape

(32, 5)

In [9]:
df2=df.dropna()
df2.shape

(29, 5)

In [1]:
from matplotlib.artist import ArtistInspector
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(arr)
print(df)

[[1 2 3]
 [4 5 6]]
   A  B  C
0  1  2  3
1  4  5  6


In [3]:

print(np.sum(arr, axis=0))
np.sum(arr, axis=1)  # across 

[5 7 9]


array([ 6, 15])

In [11]:
df3 = df.dropna(axis=1)
df3.shape

(32, 3)

In [12]:
df2 = df.dropna()
df2.shape

(29, 5)

In [13]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [14]:
df.dropna(inplace =True)
df.shape

(29, 5)

In [19]:
df=pd.DataFrame({"rollno":[1,2,3,4,5], "name":["Alice","Bob","Charlie","David","Eve"],"chemistry":[85,90,95,80,88],"maths":[90,92,88,85,91],"comp":[80,85,90,95,88]},index=[1,2,3,4,5])
df.head()

,rollno,name,chemistry,maths,comp
1,1,Alice,85,90,80
2,2,Bob,90,92,85
3,3,Charlie,95,88,90
4,4,David,80,85,95
5,5,Eve,88,91,88


In [16]:
df.isnull().sum()

rollno       0
name         0
chemistry    0
maths        0
comp         0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   rollno     5 non-null      int64 
 1   name       5 non-null      object
 2   chemistry  5 non-null      int64 
 3   maths      5 non-null      int64 
 4   comp       5 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes


In [18]:
df.describe()

,rollno,chemistry,maths,comp
count,5.000000,5.00000,5.000000,5.00000
mean,3.000000,87.60000,89.200000,87.60000
std,1.581139,5.59464,2.774887,5.59464
min,1.000000,80.00000,85.000000,80.00000
25%,2.000000,85.00000,88.000000,85.00000
50%,3.000000,88.00000,90.000000,88.00000
75%,4.000000,90.00000,91.000000,90.00000
max,5.000000,95.00000,92.000000,95.00000
