In [1]:
import numpy as np

In [3]:
np.random.random(1)

array([0.83575479])

In [4]:
np.random.random(2)

array([0.16390947, 0.10044339])

In [16]:
np.random.random((2,3))

array([[0.11858594, 0.78459281, 0.40284573],
       [0.20523761, 0.93097587, 0.4694072 ]])

In [27]:
np.random.randint(1,10,(2,2))

array([[9, 8],
       [1, 5]])

In [17]:
np.random.randint(1,10,(3,4,5))

array([[[8, 4, 8, 4, 5],
        [2, 2, 5, 4, 2],
        [2, 1, 3, 8, 4],
        [6, 8, 3, 2, 8]],

       [[2, 9, 2, 4, 8],
        [9, 4, 5, 1, 1],
        [1, 1, 1, 4, 5],
        [2, 5, 1, 8, 4]],

       [[1, 8, 8, 6, 3],
        [8, 7, 6, 3, 1],
        [3, 4, 1, 8, 8],
        [9, 9, 6, 8, 7]]])

In [18]:
np.random.rand(2,2)

array([[0.03539018, 0.74758316],
       [0.93714545, 0.87982346]])

In [19]:
np.random.randn(2,2)

array([[ 0.50718455, -0.19021326],
       [-1.14895128,  1.58231323]])

In [22]:
a=np.arange(10)
np.random.choice(a)


9

In [26]:
a=np.array([
    [[1,2,3,4,5],
     [6,7,8,9,10]],
    [[11,12,13,14,15],
     [16,17,18,19,20]]
            ])
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [28]:
s1= "My name is Tejas"
s2 = "I am an Indian"

np.char.add(s1,s2)

array('My name is TejasI am an Indian', dtype='<U30')

In [30]:
np.char.upper(s1)

array('MY NAME IS TEJAS', dtype='<U16')

In [31]:
np.char.lower(s1)

array('my name is tejas', dtype='<U16')

In [32]:
np.char.split(s1)

array(list(['My', 'name', 'is', 'Tejas']), dtype=object)

In [33]:
s3 = "i am a youtuber \n i make all kinds of videos"
np.char.splitlines(s3)

array(list(['i am a youtuber ', ' i make all kinds of videos']),
      dtype=object)

In [34]:
np.char.replace(s3,"i","I")

array('I am a youtuber \n I make all kInds of vIdeos', dtype='<U44')