In [1]:
import numpy as np


In [11]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [12]:
arr2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
arr3 = np.array([[[1,2],[3,4],[3,4]],[[5,6],[7,8],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]
  [3 4]]

 [[5 6]
  [7 8]
  [7 8]]]


In [22]:
print(arr1.shape)
print(arr2.shape)   
print(arr3.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)

(5,)
(2, 5)
(2, 3, 2)
2
int32
10


In [23]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
ones_array = np.ones((2, 4))

print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
arr = np.linspace(0, 1, 5)

print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [32]:
random_arr = np.random.randint(1, 100, size=(3, 4))

print(random_arr)

[[38 29 61 92]
 [29 73  9 44]
 [35 30 28 99]]


In [33]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [34]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix[0, 1])

2


In [35]:
arr = np.array([1, 2, 3, 4])

print(arr + 10)
print(arr * 2)
print(arr / 2)

[11 12 13 14]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [36]:
marks = np.array([78, 85, 90, 67, 95])

print("Mean:", np.mean(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))
print("Sum:", np.sum(marks))
print("Standard Deviation:", np.std(marks))

Mean: 83.0
Max: 95
Min: 67
Sum: 415
Standard Deviation: 9.777525249264253


In [38]:
marks = np.array([
    [78, 85, 90],
    [45, 50, 55],
    [88, 92, 95]
])
print(np.mean(marks,axis=0))
print(np.mean(marks,axis=1))

[70.33333333 75.66666667 80.        ]
[84.33333333 50.         91.66666667]


In [40]:
arr = np.arange(1, 13)
print(arr)
reshaped = arr.reshape(3, 4)

print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
student_marks = np.array([
    [78, 85, 90, 67],
    [45, 56, 40, 50],
    [88, 92, 95, 91],
    [60, 65, 70, 72],
    [30, 35, 28, 40]
])

print("Dataset:\n")
print(student_marks)

Dataset:

[[78 85 90 67]
 [45 56 40 50]
 [88 92 95 91]
 [60 65 70 72]
 [30 35 28 40]]


In [42]:
student_avg = np.mean(student_marks, axis=1)

print("\nStudent Average:")
print(student_avg)


Student Average:
[80.   47.75 91.5  66.75 33.25]


In [44]:
subject_avg = np.mean(student_marks, axis=0)

print("\nSubject Average:")
print(subject_avg)


Subject Average:
[60.2 66.6 64.6 64. ]


In [46]:
total_marks = np.sum(student_marks, axis=1)
print(total_marks)
topper_index = np.argmax(total_marks)

print("\nTopper Index:", topper_index)

[320 191 366 267 133]

Topper Index: 2


In [47]:
highest_marks = np.max(student_marks, axis=0)
print("\nHighest Marks in Each Subject:"   )
print(highest_marks)


Highest Marks in Each Subject:
[88 92 95 91]


In [48]:
min_val = np.min(student_marks)
max_val = np.max(student_marks)
print("\nMinimum Value:", min_val)
print("Maximum Value:", max_val)
print(student_marks)
normalized = (student_marks - min_val) / (max_val - min_val)

print(normalized)


Minimum Value: 28
Maximum Value: 95
[[78 85 90 67]
 [45 56 40 50]
 [88 92 95 91]
 [60 65 70 72]
 [30 35 28 40]]
[[0.74626866 0.85074627 0.92537313 0.58208955]
 [0.25373134 0.41791045 0.17910448 0.32835821]
 [0.89552239 0.95522388 1.         0.94029851]
 [0.47761194 0.55223881 0.62686567 0.65671642]
 [0.02985075 0.10447761 0.         0.17910448]]


In [50]:
new_arr = np.random.randint(1, 100, size=(3, 4))
print(new_arr)

[[88  3 79 42]
 [56 85 74 76]
 [83  2 92 92]]
